// apps/budget/src/app/NxWelcome.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { createSelector } from '@reduxjs/toolkit';
import { budget, store } from '@micro-frontend-tutorial/shared';

// Define component props
defineProps<{
  title: string;
}>();

// Reactive state
const count = ref(0);

// Selector for the counter slice
const selectCounterSlice = createSelector(
  (state: any) => state.counter,
  (counter) => counter
);

// Function to synchronize the store state with the local state
const syncStoreState = () => {
  const currentSlice = selectCounterSlice(store.getState());
  if (count.value !== currentSlice.value) {
    count.value = currentSlice.value;
  }
};

// Subscribe to store updates
let unsubscribe: () => void;

onMounted(() => {
  // Sync initial state
  syncStoreState();

  // Subscribe to store changes
  unsubscribe = store.subscribe(syncStoreState);
});

onUnmounted(() => {
  // Clean up the subscription
  if (unsubscribe) {
    unsubscribe();
  }
});
</script>

<template>
  <div class="wrapper">
    <div class="container">
      <div id="welcome">
        <h1>
          <span> Hello there, </span>
          Welcome {{ title }} {{ count }} 👋
        </h1>
        <button @click="store.dispatch(budget())">Budget</button>
      </div>
    </div>
  </div>
</template>

// apps/dashboard/src/app/nx-welcome.tsx
import { useSelector } from "react-redux";
import { RootState } from "@micro-frontend-tutorial/shared";

/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 This is a starter component and can be deleted.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 Delete this file and get started with your project!
 * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 */
export function NxWelcome({ title }: { title: string }) {
  const count = useSelector<RootState>((state) => state.counter.value) as number;
  return (
    <>
      <div className="wrapper">
        <div className="container">
          <div id="welcome">
            <h1>
              <span> Hello there, </span>
              Welcome {title} ({count}) 👋
            </h1>
          </div>
        </div>
      </div>
    </>
  );
}

export default NxWelcome;
